// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByCZddA-uYIHMsGGgUb_Qc96XqQDJv9tA',
    appId: '1:820829402028:web:0332d4af02b89b02458009',
    messagingSenderId: '820829402028',
    projectId: 'mobileapps-b408e',
    authDomain: 'mobileapps-b408e.firebaseapp.com',
    storageBucket: 'mobileapps-b408e.appspot.com',
    measurementId: 'G-4E8B427VB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv4YsFpn81Huni1N-K3vEc2KupUJuZgHA',
    appId: '1:820829402028:android:360a50603144755d458009',
    messagingSenderId: '820829402028',
    projectId: 'mobileapps-b408e',
    storageBucket: 'mobileapps-b408e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5IeE5o5T7P9Gitjyo7OZOFT-EAYQWED0',
    appId: '1:820829402028:ios:f879aebbc53e1124458009',
    messagingSenderId: '820829402028',
    projectId: 'mobileapps-b408e',
    storageBucket: 'mobileapps-b408e.appspot.com',
    iosClientId: '820829402028-tjmudfg63t3bse8un2q944htcsu6bmka.apps.googleusercontent.com',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5IeE5o5T7P9Gitjyo7OZOFT-EAYQWED0',
    appId: '1:820829402028:ios:f879aebbc53e1124458009',
    messagingSenderId: '820829402028',
    projectId: 'mobileapps-b408e',
    storageBucket: 'mobileapps-b408e.appspot.com',
    iosClientId: '820829402028-tjmudfg63t3bse8un2q944htcsu6bmka.apps.googleusercontent.com',
    iosBundleId: 'com.example.myproject',
  );
}
